# Generated by Django 4.0.6 on 2022-07-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='date',
            field=models.DateField(verbose_name='follow-up date'),
        ),
    ]
