# Generated by Django 4.0.6 on 2022-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_followup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('J', 'Junior'), ('M', 'Mid-Level'), ('S', 'Senior')], default='J', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-date']},
        ),
    ]
