# Generated by Django 4.0.6 on 2022-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_tech_stack_alter_followup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tech_stack',
            field=models.ManyToManyField(to='main_app.tech_stack'),
        ),
    ]
