# Generated by Django 4.0.6 on 2022-07-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_job_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_stack',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior')], default='Junior', max_length=10),
        ),
    ]
