# Generated by Django 4.0.6 on 2022-07-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_stack',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
